### ISSUE TITLE
Anyone can view a user's information even without logging in

### ISSUE THREAD

**Issue by emadehsan** [HospitalRun/hospitalrun-server-routes#1]
Anyone can view a user's information by providing his/her username.

[Problem is here](https://github.com/HospitalRun/hospitalrun-server-routes/blob/master/routes/30-auth.js#L195-L215)

![Screen shot](http://i.imgur.com/2lQDARM.png)

**Steps to generate**
Do a POST request to `http://SERVER_URL:PORT/chkuser` with a parameter `name`. Set the value of `name` equal to the name of a valid HospitalRun user

**Comment by jkleinsc** [comment]
Resolved by #2
